# multizone_office_simple_air_peak_heat_day_dynamic

# Define path and file names
path_to_dataset: '../data/boptest_dataset'
database_file_name: 'demo_kpi_validation_calculation.db'
brick_model_file_name: "multizone_office_simple_air.ttl"
updated_brick_model_file_name: "multizone_office_simple_air_with_data.ttl"

# Define the scenarios (csv file names) to analyse as baseline and flexible scenarios
baseline_scenario: 'baseline_dataset'
flexible_scenario: 'flexible_dataset'

# Define a start and end time for the evaluation period 
evaluation_timestamps:
    start: '1970-01-20 00:00:00'
    end: '1970-02-02 23:59:59'

# Define input parameters not available in the Brick model
price_signal_file_name: "scheduleData_dataset.csv"
timestamp_identifier: 'time'
price_signal_identifier: 'PriceElectricPowerHighlyDynamic'
shift_window: 2  # Set the number of hours for shift period
#rebound_window: 2  # Set the number of hours for rebound period
