from typing import List, Union
from energy_flexibility_kpis.kpi.base import KPI

class FlexibilitySavingsIndex(KPI):
    """The fraction of saved cost from a penalty-aware operational strategy (flexible) 
    compared with a penalty-ignorant operation strategy (baseline)."""

    def __init__(*args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

    def calculate(self) -> Union[float, List[float]]:
        _ = super().calculate()
        raise NotImplementedError
    
class CostOrEnergyDeviationRatio(KPI):
    """Flexibility is assessed by the energy consumption and cost deviations resulting from 
    DR measures with respect a reference scenario without DR."""

    def __init__(*args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

    def calculate(self) -> Union[float, List[float]]:
        _ = super().calculate()
        raise NotImplementedError
    
class RelativeOperationalCostOfADR(KPI):
    """Ratio between the total operational cost with ADR and the total operational 
    cost in the case of no ADR participation (only fuel cost)."""

    def __init__(*args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

    def calculate(self) -> Union[float, List[float]]:
        _ = super().calculate()
        raise NotImplementedError
    
class CostSavings(KPI):
    """Economic savings generated by the demand response of the building when 
    sold on the flexibility market."""

    def __init__(*args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

    def calculate(self) -> Union[float, List[float]]:
        _ = super().calculate()
        raise NotImplementedError